// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY_jJVdAaaIgBwhXIgfiFZ6Lk-zb0ai4Q',
    appId: '1:880015295608:web:98fc8797cc0d730967598d',
    messagingSenderId: '880015295608',
    projectId: 'meatbites-6a65c',
    authDomain: 'meatbites-6a65c.firebaseapp.com',
    storageBucket: 'meatbites-6a65c.firebasestorage.app',
    measurementId: 'G-ZS3XJBYH90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZaZ4RZuGFGmfy1phK8WPR13jxfAB2SRQ',
    appId: '1:880015295608:android:2cb8227c91add3ba67598d',
    messagingSenderId: '880015295608',
    projectId: 'meatbites-6a65c',
    storageBucket: 'meatbites-6a65c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa8EMLPh5axqFfieqZimhSLBb69t7WCWs',
    appId: '1:880015295608:ios:da101400e9ff975867598d',
    messagingSenderId: '880015295608',
    projectId: 'meatbites-6a65c',
    storageBucket: 'meatbites-6a65c.firebasestorage.app',
    iosClientId: '880015295608-7ebcd8uug4cqp0d5m57h7huvmbte15kc.apps.googleusercontent.com',
    iosBundleId: 'com.meatbites',
  );

}